### ISSUE TITLE
Usage of footers and other markdown extension

### ISSUE THREAD

**Issue by NioDeBacker** [apple/swift-markdown#115]
I am using DocC and trying to add a footnote (using `[^1]` this is possible in gfm, including cmark-gfm) but it doesn't work. Can someone tell me if this has been implemented or is going to be implemented in swift-markdown?

Example footnote [^1]

[^1]: Explanation of footnote

**Comment by QuietMisdreavus** [comment]
Footnotes are enabled in cmark-gfm (and swift-cmark) via an option passed to the parser. We currently do not enable footnotes:

https://github.com/apple/swift-markdown/blob/ad0b81fed55c4a72fdaeb5535884bd2886de96f4/Sources/Markdown/Parser/CommonMarkConverter.swift#L598-L601

It's possible to add it there to turn it on, though i'd want to make sure that we supported it properly in the MarkupWalker protocols and rendered it properly in Swift-DocC and Swift-DocC-Render to be confident in it.

**Comment by NioDeBacker** [comment]
Okay thank you for the information!

**Comment by junyan72** [comment]
Hello, any future plans to enable the support for footnotes?

**Comment by ramonfsk** [comment]
hit this gap directly in [SwiftStreamingMarkdown](https://github.com/microsoft/SwiftStreamingMarkdown): with no footnote parsing here, I ended up preprocessing [^id] into a marker before handing text to swift-markdown — works, but it's a stopgap, not native support.

happy to help if there's appetite — parser option + node types + MarkupWalker support, following how tables/tasklists/strikethrough are already modeled. let me know if a design direction exists already or if it'd help to sketch one first.
