### ISSUE TITLE
How to add custom syntax ?

### ISSUE THREAD

**Issue by tienll** [apple/swift-markdown#122]
How to add custom syntax to support latex or something else?

**Comment by danpalmer** [comment]
You can write custom "directives". If you're implementing a `MarkupVisitor`/`MarkupRewriter` you need to implement `visitBlockDirective`.

The syntax is a leading `@` symbol, a name, an optional argument list with the first argument name being optional, and an optional `{}` brace delimited child document.

For example:

```markdown
@LaTeX {
    This is a \LaTeX{} document
}
```

This would parse as a `BlockDirective` with name `LaTeX`, and children being a `Text` element containing the text. From here you can extract this, replace it with something else, or do whatever you like.
