### ISSUE TITLE
How to use this package to render markdown text in SwiftUI or UIKit?

### ISSUE THREAD

**Issue by Elamuruga** [apple/swift-markdown#131]
import Markdown

let source = "This is a markup *document*."
let document = Document(parsing: source)
print(document.debugDescription())
// Document
// └─ Paragraph
//    ├─ Text "This is a markup "
//    ├─ Emphasis
//    │  └─ Text "document"
//    └─ Text "."

Anyone, could you help me to guide how to use this to display markdown text? Thanks in advance.

**Comment by QuietMisdreavus** [comment]
Hello! As-is, Swift-Markdown only outputs an abstract representation of the parsed Markdown. To convert it into an `NSAttributedString` for use in SwiftUI or UIKit, you'd need to do that conversion separately.

Community member @christianselig wrote up a single-file library to do that conversion: https://github.com/christianselig/Markdownosaur Does that fit your needs?

**Comment by Elamuruga** [comment]
> Hello! As-is, Swift-Markdown only outputs an abstract representation of the parsed Markdown. To convert it into an `NSAttributedString` for use in SwiftUI or UIKit, you'd need to do that conversion separately.
> 
> Community member @christianselig wrote up a single-file library to do that conversion: https://github.com/christianselig/Markdownosaur Does that fit your needs?

Thank you for your immediate response it really helps me and saves my day.  Once again thank you lot  @QuietMisdreavus

**Comment by GIKICoder** [comment]
Thank you. Based on the idea of Markdownosaur, I have implemented a new markdown renderer using UIKit.
If you have any further markdown rendering needs, you can try this one.  [GMarkdown](https://github.com/GIKICoder/GMarkRender )
