### ISSUE TITLE
Unexpected symbol link source range

### ISSUE THREAD

**Issue by arthurcro** [apple/swift-markdown#142]
## Summary 

When parsing a symbol link with multiline content, the source range is unexpected, new lines are replaced by whitespaces. 

For instance, parsing the following symbol link:

```
Test of a ``multi
line symbolink``
```

gives a symbol link with a range of `1:11-1:35`. Which is the equivalent of:

```
Test of a ``multi line symbolink``
```

 However, I would rather expect either:

- A range of `1:11-2:17`
- An invalid symbol link

## Steps to reproduce

```swift
let source = """
Test of a ``multi
line symbolink``
"""
let document = Document(parsing: source, options: .parseSymbolLinks)
print(document.debugDescription(options: .printEverything))
```

```
Document @1:1-2:17 Root #1 #0
└─ Paragraph @1:1-2:17 #1
   ├─ Text @1:1-1:11 #2 "Test of a "
   └─ SymbolLink @1:11-1:35 #3 destination: multi line symbolink
```
## Notes

This is a suspected cause of a crash in DocC diagnostic formatter. https://github.com/apple/swift-docc/issues/678#issuecomment-1684914893

**Comment by Kyle-Ye** [comment]
Looks like the bug is in the upstream cmark 🤔

cmark_node_get_end_line(node) for the symbollink node is giving 1 instead of 2.

<img width="1728" alt="image" src="https://github.com/apple/swift-markdown/assets/43724855/06ecfa6b-c3a2-4cf3-8a2a-3f4b0cfb7019">

**Comment by Kyle-Ye** [comment]
The issue seems to be `adjust_subj_node_newlines` in inlines.c

https://github.com/apple/swift-cmark/blob/3bc2f3e25df0cecc5dc269f7ccae65d0f386f06a/src/inlines.c#L402-L423
