### ISSUE TITLE
How to support a link with space?

### ISSUE THREAD

**Issue by tienll** [apple/swift-markdown#155]
For example,

`[Title](Link To The Resource)`

The parsing is failed due to the space, is that possible to somehow make it work?

**Comment by QuietMisdreavus** [comment]
It looks like [the GitHub-Flavored Markdown spec](https://github.github.com/gfm/#links) (which Swift-Markdown uses as a base) allows link destinations with spaces if you wrap them in angle brackets:

```markdown
[Title](<Link To The Resource>)
```

**Comment by tienll** [comment]
> It looks like [the GitHub-Flavored Markdown spec](https://github.github.com/gfm/#links) (which Swift-Markdown uses as a base) allows link destinations with spaces if you wrap them in angle brackets:
> 
> ```
> [Title](<Link To The Resource>)
> ```

Thanks, that's a good solution!
