### ISSUE TITLE
Does this SDK need a Privacy Manifest?

### ISSUE THREAD

**Issue by tinder-jaylinphipps** [apple/swift-markdown#172]
With the latest changes to apples privacy manifest requirements. Does using this SDK require the need for a privacy manifest?

Reference:
https://developer.apple.com/support/third-party-SDK-requirements/#:~:text=Starting%20in%20spring%202024%2C%20you,as%20part%20of%20the%20update.

**Comment by Kyle-Ye** [comment]
No.

1. This package does not collect data or send them.
2. The package is not listed as "SDKs that require a privacy manifest and signature" in your link.
