### ISSUE TITLE
Add Snippets playground support

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-markdown#52]
Add Playground or Snippets Support, so that people can quickly play with Markdown API

**Comment by Kyle-Ye** [comment]
#53 adds a simple implementation of playground.(Which is only supported on macOS)

I think a better solution is adopting and using Swift Snippests.

> ## Snippets as playgrounds
>
> Why aren’t these just playgrounds? While playgrounds started out very similarly to snippets, they have evolved into something more powerful, more tied to custom tooling, and a bit more complex. Playgrounds tend to tell a story, and are stand-alone entities with their own supporting files and sources.
> 
> For open source Swift, packages already have a model for building targets that have multiple files and resources, and in fact, we’re seeing playgrounds migrating more toward looking like packages.
>
> Snippets are intentionally small programs written as a simple .swift file, integrated closely with the Swift Package Manager approach, as is Swift-DocC.

Once Swift-Snippets lands the release of swift, I’ll update the implementation.

See full proposal on Snippets here. https://github.com/apple/swift-evolution/blob/main/proposals/0356-swift-snippets.md

**Comment by franklinsch** [comment]
I agree for using Snippets rather than Playgrounds so that they can be used on all platforms rather than just macOS.
