### ISSUE TITLE
Including a @Comment in silently breaks symbol's doc rendering

### ISSUE THREAD

**Issue by ktoso** [apple/swift-markdown#64]
### Description

Let's say I have a symbol `Example`.

In my `Sources/ExampleThing/ExampleThing.docc/Example.md` i have

```md
# ``Example``

@Comment { Don't forget X }

## More things here

Lorem ipsum...
```

This silently breaks the rendering of the entire page's rendering -- it appears completely empty and no warnings are emitted either.

I'm guessing `@Comment` can only be used in a tutorial -- which is a bit meh... the syntax should be the same in al types of files.

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

The @Comment should work as expected -- just not be rendered.

### Actual behavior

The rendering of the entire documentation page for the symbol is empty / broken by the presence of a `@Comment`

### Steps To Reproduce

- document any symbol
- add `@Comment { hello }`
- observe the comment prevented content, other than the sub-title from being rendered

### Swift-DocC Version Information

5.7

### Swift Compiler Version Information

```shell
-> % swift --version
swift-driver version: 1.62.1 Apple Swift version 5.7 (swiftlang-5.7.0.123.6 clang-1400.0.29.50)
```

**Comment by ktoso** [comment]
I can confirm the workaround works and we've worked around this in https://github.com/apple/swift-distributed-actors/pull/1027 for now.

**Comment by Kyle-Ye** [comment]
Update:
The Article will be properly parsed at some time as the following after #66, but still renders the wrong output.
I'm digging it to find more info.
```
# Example

@Comment { Don't forget X }

asdfsda

## More things here

Lorem ipsum...
```

```
Document
├─ Heading level: 1
│  └─ Text \"Example\"
├─ BlockDirective name: \"Comment\"
│  └─ Paragraph
│     └─ Text \"Don’t forget X\"
├─ Paragraph
│  └─ Text \"asdfsda\"
├─ Heading level: 2
│  └─ Text \"More things here\"
└─ Paragraph
   └─ Text \"Lorem ipsum\"
```

**Comment by Kyle-Ye** [comment]
Also in case 2, the Xcode's rendering looks like a bug for me.

I've filed it to Feedback as FB11157755.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/43724855/183559941-9d534d0a-7bea-48b8-bcb5-8c08f8afec35.png">
